name: Build and test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core
        run: ./src/Giraffe/Core.fs
